name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: code/
        run: |
          chmod +x ./init.sh
          ./init.sh

      - name: Build
        working-directory: code/
        run: |
          chmod +x ./ci_build.sh
          ./ci_build.sh > build.log 2>&1 || (cat build.log && exit 1)

      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: code/build/