name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libsndfile1-dev libasound2-dev libgtest-dev

          # Manually build GTest if system GTest headers are available but libs are not
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo cp lib/*.a /usr/lib

          chmod +x code/init.sh
          ./code/init.sh

      - name: Build
        run: |
          chmod +x code/build.sh
          ./code/build.sh > build.log 2>&1

      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: code/build/

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: code/build

      - name: Run unit tests
        working-directory: code/build/src/test/unit_tests
        run: |
          ctest --output-on-failure

  lint:
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true
    steps:
      - name: Download build log
        uses: actions/download-artifact@v4
        with:
          name: build-log
          path: .

      - name: Check for warnings in the build log
        run: |
          cat build.log
          ! grep -q "warning:" build.log
